version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - bragi-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./storage:/var/www/storage:ro
    depends_on:
      - api
    networks:
      - bragi-network

networks:
  bragi-network:
    driver: bridge
